CREATE TABLE IF NOT EXISTS workpasses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_date  TIMESTAMP WITHOUT TIME ZONE,
    expire_date TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    is_handed  BOOLEAN,
    CONSTRAINT pk_workpasses PRIMARY KEY (id)
);
