CREATE TABLE IF NOT EXISTS photos_pass
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url         VARCHAR(255),
    file_name   VARCHAR(255),
    create_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT photos_pass_pkey PRIMARY KEY (id)
);
